### PR TITLE
Add YamahaExtendedControl, add client app

### PR DESCRIPTION
**Pull request by rmarinho**
Add a client app that will work as a test for a client sdk to talk with the speakers.

IP hardcoded , run the project, turns it on and off using C and D on the command line

### CODE REVIEW

**Comment by neutmute** [comment]
nice one!

**Comment by neutmute** [comment]
Hey so this doesn't compile for me. I merged anyway to keep things rolling.

Compiling client for .NETCoreApp,Version=v1.0
C:\CodeHome\swimbait\client\project.json(9,60): error NU1001: The dependency Microsoft.AspNetCore.Diagnostics >= 1.1.0-alpha1-22144 could not be resolved.
C:\CodeHome\swimbait\client\project.json(10,56): error NU1001: The dependency Microsoft.AspNetCore.Hosting >= 1.1.0-alpha1-22144 could not be resolved.
C:\CodeHome\swimbait\client\project.json(13,70): error NU1001: The dependency Microsoft.AspNetCore.Server.IISIntegration >= 1.1.0-alpha1-22144 could not be resolved.
C:\CodeHome\swimbait\client\project.json(14,63): error NU1001: The dependency Microsoft.AspNetCore.Server.Kestrel >= 1.1.0-alpha1-22144 could not be resolved.
C:\CodeHome\swimbait\client\project.json(15,60): error NU1001: The dependency Microsoft.AspNetCore.StaticFiles >= 1.1.0-alpha1-22144 could not be resolved.
C:\CodeHome\swimbait\client\project.json(16,62): error NU1001: The dependency Microsoft.Extensions.Configuration >= 1.1.0-alpha1-22144 could not be resolved.
C:\CodeHome\swimbait\client\project.json(18,64): error NU1001: The dependency Microsoft.Extensions.Configuration >= 1.1.0-alpha1-22144 could not be resolved.
C:\CodeHome\swimbait\client\project.json(19,54): error NU1001: The dependency Microsoft.Extensions.Configuration >= 1.1.0-alpha1-22144 could not be resolved.
C:\CodeHome\swimbait\client\project.json(16,62): error NU1001: The dependency Microsoft.Extensions.Configuration >= 1.0.0 could not be resolved.
C:\CodeHome\swimbait\client\project.json(18,64): error NU1001: The dependency Microsoft.Extensions.Configuration >= 1.0.0 could not be resolved.
C:\CodeHome\swimbait\client\project.json(19,54): error NU1001: The dependency Microsoft.Extensions.Configuration >= 1.0.0 could not be resolved.
C:\CodeHome\swimbait\client\project.json(17,74): error NU1001: The dependency Microsoft.Extensions.Configuration.CommandLine >= 1.1.0-alpha1-22144 could not be resolved.
C:\CodeHome\swimbait\client\project.json(20,64): error NU1001: The dependency Microsoft.Extensions.Logging.Console >= 1.1.0-alpha1-22144 could not be resolved.

**Comment by rmarinho** [comment]
i m very cutting edge :) i m using the alpha channel , playing with signalr also in other project.

https://dotnet.myget.org/gallery/aspnetcore-dev

**Comment by neutmute** [comment]
cool - fixed 
https://github.com/neutmute/swimbait/commit/5be2ca4eb83a27f666eb04a44ee45cae50d3716a

**Pull request merged**
